### ISSUE TITLE
Emails not propagating into app

### ISSUE THREAD

**Issue by rememberlenny** [wingrunr21/griddler-mandrill#25]
Emails are not propagating into the app. After setting up Mandrill, and confirming the Test emails process, any emails sent to the app do not process into requests to the app. 

The only payload that is accessible via the app, setup through Mandrill, is the Test requests. Any of the test requests are visible via Pry or network requests. 

Any of the email_processor POST requests do not trigger for regular email requests, regardless of the Mandrill configuration.

I used a variety of settings for the email routes, including a wildcard address and specific URL. Neither was working locally (via ngrok) or on Heroku.

**Comment by LArunkumar** [comment]
+1... Given how this is unanswered for days, I guess I will write my own parser... May I ask how you solved this?

**Comment by wingrunr21** [comment]
This is unanswered because I have nothing to debug with. Are you seeing your real requests hit rails?
